# ----------------------------------------------------------------------------------
# Project: CrystalSweep
# File: pyproject.toml
# ----------------------------------------------------------------------------------
# Purpose:
# This file is used to specify the project configuration and dependencies.
# ----------------------------------------------------------------------------------
# Author: Christofanis Skordas
#
# Copyright (c) 2026 GSECARS, The University of Chicago, USA
# Copyright (c) 2026 NSF SEES, USA
# ----------------------------------------------------------------------------------

[project]
name = "roadster"
version = "0.1.3"
authors = [
    {name = "Christofanis Skordas", email = "55315750+skordaschristofanis@users.noreply.github.com"}
]
maintainers = [
    {name = "Christofanis Skordas", email = "55315750+skordaschristofanis@users.noreply.github.com"}
]
description = "Python GUI application for absorption scanning."
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
classifiers = [
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.14",
    "License :: OSI Approved :: MIT License"
]
requires-python = "==3.14.*"
dependencies = [
    "lmfit>=1.3.4",
    "newportxps>=2026.1.1",
    "numpy>=2.5.2",
    "pyautomation>=0.0.1",
    "pyepics>=3.5.10",
    "pyqt5>=5.15.11",
    "pyqtgraph>=0.14.0",
    "pyshortcuts>=1.9.10",
    "qtpy>=2.4.3",
]

[project.scripts]
roadster = "roadster:main"

[project.urls]
Homepage = "https://github.com/GSECARS/Roadster"
Issues = "https://github.com/GSECARS/Roadster/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["roadster"]
include = ["roadster/assets/**"]

[tool.ruff]
exclude = [
    ".eggs",
    ".git",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".venv",
    ".vscode",
    "build",
    "dist",
]
line-length = 160
indent-width = 4
target-version = "py313"

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
ignore = []
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false
docstring-code-line-length = "dynamic"
